### ISSUE TITLE
运行代码发现错误

### ISSUE THREAD

**Issue by DiuDiu-1123** [david-knigge/ccnn#12]
\ccnn-main\dataset_constructor.py", line 31, in construct_datamodule
    dataset = getattr(datamodules, dataset_name)
AttributeError: module 'datamodules' has no attribute 'DataModule'

how can i solve this problem?

**Comment by dwromero** [comment]
Hi @DiuDiu-1123,

I think that the problem is that you are not defining an specific datamodule. You can select one by adding modifying the argument dataset.name, e.g., dataset.name==CIFAR10

**Comment by DiuDiu-1123** [comment]
I didn't find model checkpoints you provided, can you send them to me？Thank you very much!

**Comment by Shaoqi-Wang** [comment]
I think you need to appoint a specific datamodule to get code work, so as to other parts,  all default has been set to -1 or '', see the experiments file for more information?

**Comment by DiuDiu-1123** [comment]
> Hi @DiuDiu-1123,
> 
> I think that the problem is that you are not defining an specific datamodule. You can select one by adding modifying the argument dataset.name, e.g., dataset.name==CIFAR10.
> 
> See https://github.com/david-knigge/ccnn/tree/main/experiments and the README file for more information regarding the arguments.
> 
> David

Thank you for your reply. I have solved it.
