### ISSUE TITLE
运行代码发现错误

### ISSUE THREAD

**Issue by Big-Rabbit-Ear** [david-knigge/ccnn#2]
\ccnn-main\ckconv\nn\functional\causal_conv.py", line 11, in <module>
    ) -> tuple[torch.Tensor, torch.Tensor]:
TypeError: 'type' object is not subscriptable

**Comment by BJFU-CS2012** [comment]
> 

How did you solve it？It's also a problem for me

**Comment by david-knigge** [comment]
Hi! Are you sure you are using python 3.9 (see requirements.yml)? [Support was added in 3.9](https://docs.python.org/3.9/library/typing.html#typing.Tuple) for indexing the built-in `tuple` directly, could it be you are running an older version?

**Comment by dwromero** [comment]
You can solve this in other python versions by adding

`from typing import Tuple`

and use `Tuple` instead of `tuple` in the definition of types in functions.

**Comment by BJFU-CS2012** [comment]
> Hi! Are you sure you are using python 3.9 (see environment.yml)? [Support was added in 3.9](https://docs.python.org/3.9/library/typing.html#typing.Tuple) for indexing the built-in `tuple` directly, could it be you are running an older version?

 Thank you for your reply,I'm sorry to waste your time you are right my python version is 3.8 and I solved this issue through using 'from typing import Optional,Tuple' and use Tuple instead of tuple ;

**Comment by BJFU-CS2012** [comment]
> You can solve this in other python versions by adding
> 
> `from typing import Tuple`
> 
> and use `Tuple` instead of `tuple` in the definition of types in functions. Same holds for `Dict` and `List`.

thank you for your i help i have solved this problem. I'm sorry to waste your time because i'm still a novice in scientific research

**Comment by dwromero** [comment]
No need to apologize at all! :) happy to be of help! 


Please let us know if you have any other questions! 

Cheers, 
David
