### ISSUE TITLE
how to input the irregular sampled data, such as sparse images

### ISSUE THREAD

**Issue by cyx669521** [david-knigge/ccnn#8]
Thank you very much for sharing such interesting work. I am wondering if you are convenient to show me how to input sparse images into your network.  For example, we input the sparse values according to the coordinates of existing points in images.

**Comment by dwromero** [comment]
Dear @cyx669521 

We apologize for the late response. 

We are coming back from holiday next week and will upload the code to do prediction on irregularly sampled data soon after we arrive.

I must say, however, that from a computational point of view, it is better to use regular grids whenever possible. For instance, if in your application you want to do prediction on certain pixels, it is computationally advantageous to use a mask and set all irrelevant values to zero. The reason for this is that in point-clouds new kernels need to be rendered for each point. If one is able to define the input in a grid, however, this can be alleviated.

Best,
David

**Comment by cyx669521** [comment]
Thank you so much~

**Comment by cyx669521** [comment]
I am very sorry to push you on this issue. I completely understand what you said here. However, the zero masks must affect the convolution result.

**Comment by dwromero** [comment]
Hi Yusin,

we have added a new PR with the code for irregular data. Please let us know if you have any questions :)

Cheers,
David
